Issue #4: Added the ability to add new items to the list and save to the db
the-collab-lab/tcl-31-smart-shopping-list pull request #19
Opened 2021-10-11 16:24 UTC by aidantorrence

## Description

Created a form for users to enter item names and how soon they anticipate purchasing items (soon, kind of soon, not soon).  When users submit the form, it is saved to db associated with user's token (we generated a token 'plushy cuny idiom').  When submitting an item, a number corresponding to estimated number of days is saved.  Item names are displayed as an unordered list when added.  Deleted the button from issue #1 which was no longer needed

AC:

- [ ] User is presented with a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again (Soon, Kind of Soon, Not Soon)
- [ ] When the user submits the form, the item is saved to the database, associated with the user’s token
- [ ] Along with the item name, an integer corresponding to the estimated number of days until next purchase is saved: 7 for “Soon”, 14 for “Kind of Soon”, and 30 for “Not Soon”
- [ ] The last purchased date should be set to null initially (i.e. you can create an item without purchasing it)
- [ ] Item names should be displayed as a simple, unordered list on the list view after they’re added

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

![image](https://user-images.githubusercontent.com/26528573/136823460-bd8e37a7-b5cc-41c1-9da3-c2325c0730c9.png)

![image](https://user-images.githubusercontent.com/26528573/136823505-dd6fd2cd-3e7c-4c84-9d51-80016753b2a6.png)

### After

![image](https://user-images.githubusercontent.com/26528573/136822813-8be76a5d-7d92-4e4d-b7a9-f8665680b55e.png)

![image](https://user-images.githubusercontent.com/26528573/136822884-afb802ad-e1e6-443d-91a4-35337adfce2d.png)

![image](https://user-images.githubusercontent.com/26528573/136823022-8f5bdc59-1d2c-4cf8-94d0-80eb6d38691d.png)

2021-10-12 23:45 UTC, gabynr requested changes
Great Work!!! Your code is clear, I can read it without problem. I love that. I have a few questions 👏🏽

2021-10-12 23:45 UTC, gabynr commented on src/List.js
> +  useEffect(() => {
In the Component App you copied and modified according to the issue the Useefect Hook From App.js to List.js here  and moved the method handleClick from App.js to the new AddForm, why didn't you delete this code on the App component?

2021-10-12 23:45 UTC, gabynr commented on src/List.js
> +          return [...acc, { id, name }];
I have a question, I think that in the UseEffect you are not searching by token, which I believe means that you'll get all the items in the database. Can you test creating an item for a different list with another token, if you see all the items that are in the database?

2021-10-14 16:40 UTC, gabynr commented on src/List.js
> +          return [...acc, { id, name }];
Yes, maybe it isn't you scope in this issue . Thanks for doing that test for me!!

2021-10-17 17:42 UTC, andreamartz commented
@aidantorrence @bajancode 

@gabynr was approving on behalf of both of us. We probably could have been more clear about that, so my apologies. I just realized this morning that you are still waiting for my review.

Now that @gabynr and I have merged our PR (a few days ago), there are merge conflicts with your PR that need to be addressed. It should be pretty straightforward. Please let me know if it's not, and I can help.

2021-10-17 18:06 UTC, merged